# Generated by Django 5.1.2 on 2024-11-11 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_guardian_remove_student_parents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='guardian_full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_type',
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parent_1', to='students.parent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_2',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='parent_2', to='students.parent'),
            preserve_default=False,
        ),
    ]
