# Generated by Django 5.1.2 on 2024-11-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_delete_guardian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_assigned',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
