# Generated by Django 5.1.2 on 2024-11-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_class_class_name'),
        ('students', '0007_remove_student_class_assigned_student_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_assigned',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classes.class'),
            preserve_default=False,
        ),
    ]
