# Generated by Django 5.1.2 on 2024-11-16 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_class_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_parent_2', to='students.parent'),
        ),
    ]
