# Generated by Django 5.1.2 on 2024-11-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_parent_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
