# Generated by Django 5.1.2 on 2024-11-17 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_parent_full_name_alter_parent_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_parent_2', to='students.parent'),
        ),
    ]
