# Generated by Django 5.1.2 on 2024-11-17 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_parent_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_2', to='students.parent'),
        ),
    ]
