# Generated by Django 5.1.2 on 2024-11-14 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='grade',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='letter',
            field=models.CharField(default=6, max_length=1),
            preserve_default=False,
        ),
    ]
