# Generated by Django 5.1.2 on 2024-11-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_grade_class_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_name',
        ),
    ]
