# Generated by Django 5.1.2 on 2024-11-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_remove_contract_document_remove_contract_is_signed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='start_date',
        ),
    ]
