# Generated by Django 5.1.2 on 2024-11-17 16:09

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_remove_contract_end_date_remove_contract_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 12, 31)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
    ]
