# Generated by Django 5.1.2 on 2024-11-17 16:20

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_end_date_contract_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=contracts.models.get_end_date),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=contracts.models.get_start_date),
        ),
    ]
