# Generated by Django 5.1.2 on 2024-11-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_delete_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='subjects',
            new_name='subject',
        ),
    ]
