# Generated by Django 5.1.2 on 2024-11-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_rename_subject_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_assigned',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
