# Generated by Django 5.1.2 on 2024-11-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacher_class_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='education',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='work_experience',
        ),
    ]
