# Generated by Django 5.1.2 on 2024-11-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_alter_teacher_class_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_assigned',
        ),
    ]
