# Generated by Django 5.1.2 on 2024-11-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_remove_teacher_class_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='education_specialty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='education_university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
